name: CD Compute

on:
  push:
    branches:
      - preprod
      - prod
  workflow_dispatch:

jobs:
  jcloudify-app-deployer:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      AWS_REGION: eu-west-3
    steps:
      - uses: actions/checkout@v4.1.6

      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - uses: hei-school/aws-credentials-setter@v1.0.3
        with:
          secrets: ${{ toJSON(secrets) }}
          region: ${{ env.AWS_REGION }}

      - run: sam build

      - name: Deploy app
        run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name ${{ github.ref_name }}-compute-jcloudify-app-deployer --capabilities CAPABILITY_IAM --resolve-image-repos --parameter-overrides Env=${{ github.ref_name }} --resolve-s3 --tags app=jcloudify-api env=${{ github.ref_name }} user:poja=jcloudify-api

