name: CI

on:
  push:
    branches:
      - "*"
  workflow_dispatch:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - run: pip install black
      - run: black --check .