name: Release SAM Cli Layer

on:
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      AWS_REGION: eu-west-3
    steps:
      - uses: actions/checkout@v4.1.6

      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - uses: hei-school/aws-credentials-setter@v1.0.3
        with:
          secrets: ${{ toJSON(secrets) }}
          region: ${{ env.AWS_REGION }}

      - run: python -m pip install --upgrade pip

      - name: Build and publish preprod layer
        if: github.ref_name == 'preprod'
        run: |
          sh ./create-and-publish-aws-sam-cli-layer.sh ${{ secrets.PREPROD_BUCKET_NAME }}

      - name: Build and publish prod layer
        if: github.ref_name == 'prod'
        run: |
          sh ./create-and-publish-aws-sam-cli-layer.sh ${{ secrets.PROD_BUCKET_NAME }}